### ISSUE TITLE
1.0.2 bug: Forced prompt comparison

### ISSUE THREAD

**Issue by yoyo837** [ScooterSoftware/bcompare-vscode#8]
When I clicked one record on File History, it popped up the comparison results, but I didn't want to compare.

**Comment by boramis** [comment]
We just released v1.0.3 with this fixed.  We had to remove the "Open BC instead of the Diff Editor" option (#3) for now.  It was _supposed_ to be opt-in, not enabled by default, but the way it was implemented also didn't handle this case well and had other holes in the implementation.  Sorry for the trouble.
